# Generated by Django 4.1.7 on 2023-03-24 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categoria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='m_tipo',
            fields=[
                ('id_tipo', models.AutoField(db_column='id_tipo', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150, null=True, verbose_name='Nombre')),
                ('image', models.ImageField(blank=True, null=True, upload_to='tipo', verbose_name='Foto')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creación')),
            ],
            options={
                'verbose_name': 'Tipo',
                'verbose_name_plural': 'Tipos',
                'db_table': 'tipo',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='m_proveedor',
            fields=[
                ('id_proveedor', models.AutoField(db_column='id_proveedor', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150, null=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, max_length=500, null=True, verbose_name='Descripción')),
                ('contacto', models.CharField(max_length=150, null=True, verbose_name='Contacto')),
                ('puesto', models.CharField(blank=True, max_length=150, null=True, verbose_name='Puesto')),
                ('email', models.EmailField(max_length=150, null=True, verbose_name='Email')),
                ('tel1', models.CharField(max_length=150, null=True, verbose_name='Teléfono 1')),
                ('tel2', models.CharField(blank=True, max_length=150, null=True, verbose_name='Teléfono 2')),
                ('pais', models.CharField(blank=True, max_length=250, null=True, verbose_name='País')),
                ('estado', models.CharField(blank=True, max_length=150, null=True, verbose_name='Estado')),
                ('ciudad', models.CharField(blank=True, max_length=150, null=True, verbose_name='Ciudad')),
                ('direccion', models.CharField(blank=True, max_length=250, null=True, verbose_name='Dirección')),
                ('sitioweb', models.URLField(blank=True, max_length=250, null=True, verbose_name='Sitio Web')),
                ('facebook', models.CharField(blank=True, max_length=250, null=True, verbose_name='Facebook')),
                ('presentacion', models.FileField(blank=True, max_length=250, null=True, upload_to='', verbose_name='Presentación')),
                ('canaco', models.BooleanField(default=True, verbose_name='Canaco')),
                ('RS', models.CharField(blank=True, max_length=250, null=True, verbose_name='Razón Social')),
                ('RFC', models.CharField(blank=True, max_length=15, null=True, verbose_name='RFC')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creación')),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='categoria.m_categoria', verbose_name='Categoria')),
                ('tipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='proveedor.m_tipo', verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'proveedor',
                'ordering': ['nombre'],
            },
        ),
    ]
